### ISSUE TITLE
[FIREFOX] Website broken? 

### ISSUE THREAD

**Issue by Chalarangelo** [fejes713/30-seconds-of-interviews#102]
@atomiks @fejes713 @skatcat31 @flxwu Website seems to be broken for me. We need to address this asap!

### Notes

- This only seems  to happen on Firefox on my PC, works properly for Chrome. 
- No errors in console.

**Comment by Chalarangelo** [comment]
![screenshot_2018-09-05 30 seconds of interviews](https://user-images.githubusercontent.com/8281875/45108736-1e5c6980-b146-11e8-844b-43ea00cf59d9.png)

This is what I see on Firefoxs on my PC and after a few seconds it goes blank.

**Comment by AlejandroMataGuillen** [comment]
@Chalarangelo Just tested on Firefox 61.0.1 and works well

**Comment by atomiks** [comment]
Not seeing any problems on Firefox either (61 & 62), but that's Mac not PC

**Comment by Chalarangelo** [comment]
Can't reproduce on a similar setup (Win 10, Firefox). It's probably a problem with my home PC, so I'll check back in the afternoon, figure out the reason why.

**Comment by flxwu** [comment]
Works for me on Firefox (62) & Chrome (v. 71) aswell

**Comment by fejes713** [comment]
Thanks for testing it out @flxwu @atomiks 👍 Hopefully its just problem with @Chalarangelo PC.

I am closing this for now. If some of you run into the same issue again, feel free to reopen this as its a huge issue.

**Comment by skatcat31** [comment]
FF is known to be a browser currently undergoing some pains. It's having issues parsing large JSON(above a few KB, has been since the rework), some CSS3 logic(some real edge cases here about composition of transformations triggering other transformations), and a bad parser for date times that sometimes does not resolve the TZ(seems to be fixed as of 61 at least).

This issue however would be a parsing of inline scripts, which would be a serious problem that would have been reported as "OMGZ FireFox is broke, E'ERYONE CLICKBAIT" or something on Gizmodo and The Verge, so I'm guessing it's local.

Tested and working just fine on FF 61/62, Chrome/Canary, and M$ Edge. IF you can constantly recreate this we'd love to see a version number. Their issue tracker may have more information if we can get that

(also sorry for absence, had an event, then getting ready for reception... gonna be a busy AF month)

**Comment by fejes713** [comment]
Hey @skatcat31 Thanks for detailed report, I appreciate it very much. We should be stable now, should I close this issue or leave it here if someone encounters the same behavior?

**Comment by skatcat31** [comment]
I think it's safe to close as a "unrepeatable local problem"

**Comment by fejes713** [comment]
Closing this after receiving feedback from a few more people. Feel free to reopen if you encounter the same problem again.
