### ISSUE TITLE
Cloning an object should mention .getOwnPropertyDescriptors

### ISSUE THREAD

**Issue by mildrenben** [fejes713/30-seconds-of-interviews#68]
The question titled: How do you clone an object in JavaScript?

The answer should mention the fact that getters and setters do not get copied in the ways you've currently described and that you need to use `Object.defineProperties({}, Object.getOwnPropertyDescriptors(obj))` to get a full shallow copy including the getters and setters. Using only spread to copy makes some kinda weird stuff happen with getters/setters. Spread operator copies the result of a getter if it was ran at that time and stores it as a property, it's pretty odd. 

Here's a jsfiddle that shows what I'm talking about: https://jsfiddle.net/z3gszLmL/3/

**Comment by skatcat31** [comment]
There's two ways we can take this:

1. Assuming Objects are POJS(Plain Old Javascript) which means no Getter or Setters as then it becomes an instance of a custom type with no prototype
1. Include information about proxies(Getters, Setters, actual Proxies) and custom types and attempt to support them

I'm more for version 1 since program modification of an Object needs to be documented and should be known by the developer. At that point it's no longer an Object but a custom type as a Developer should *always* know what is happening in *their* code(after all they're the ones who maintain it)

This could open a corollary question about "How do you clone an Object with Proxy Methods?" which requires some CS knowledge on what a Proxy Method is, and thankfully can be marked Expert since this is some knowledge that most people can get by without ever actually needing, but in certain situations can be extremely useful.

**Comment by skatcat31** [comment]
Since there haven't been any other opinions expressed in the past week we'll be going with 'assume POJS' and issuing a `won't fix tag`.
